version: '3.7'

services:
    ui:
        container_name: 'movietheque-react'
        build: ./ui
        ports: 
            - 3000:3000
        depends_on:
            - api
        volumes:
            - ./ui:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
    
    api:
        container_name: 'movietheque-express'
        build: ./api
        ports:
            - 8080:8080
        depends_on: 
            - database
        volumes:
            - ./api:/usr/src/app
            - /usr/src/app/node_modules
        tty: true

    database:
        image: mongo
        container_name: 'movietheque-mongodb'
        ports:
            - 27017:27017
